version: '2'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_HOST: db
      PMA_PORT: 3306
    links:
      - mysql:db

  mysql:
    build:
      context: .
      dockerfile: dockerfile-mysql
    command: --skip-name-resolve
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

  redis:
    image: redis
    ports:
      - "6379:6379"
